### ISSUE TITLE
[chains] implement `chains make --output kubernetes`

### ISSUE THREAD

**Issue by compleatang** [monax/monax#1272]
**Problem** -- We want to be able to output k8s files as more users move to deploying into those clusters. Chains make has all of the information required to output appropriate configuration files that can then easily be consumed by a k8s cluster. 

**Solution** -- `chains make --output kubernetes` should output set of files that can be consumed by clusters. These should include the following:

* An `all_nodes.yaml` file that contains:
  * a `ConfigMap` with a condensed version of the genesis.json
  * a `Service` to the 1337 port on one of the nodes (probably commented by default) (random note, never load balance the 1337 port)
* A `keys.yaml` file that contains:
  * a range of `Secret`s which load the keys into Kubernetes secrets
* A `nodeXXX.yaml` file that contains:
  * a `Deployment` for the node which will start eris-db in "cluster mode" with the appropriate startup env vars
  * a `Service` which will expose the peer port within the cluster

**Comment by zramsay** [comment]
partially implemented in burrow (https://github.com/hyperledger/burrow/tree/master/deployment) & this issue is labeled "discussion". If we do implement, the functionality should come from burrow first and the function imported/called from cli

**Comment by zramsay** [comment]
aint gonna happen
