### ISSUE TITLE
[pkgs] sometimes return value is empty

### ISSUE THREAD

**Issue by marc4gov** [monax/monax#1407]
Please include in your bug report:

- [17.04 ] `docker version`
- [0.17 ] `monax version`
- [1.8 ] `go version` (if applicable)
- [ ] `docker-machine version` (if applicable / !linux)
- [linux ] operating system details (osx/windows/linux)
- [ ] what you expected to happen
Expecting return values for all jobs
- [ ] what actually happened
In long running jobs (> 3 min) sometimes return values are empty

- [ ] steps to reproduction

Expecting a return value for `TIE162P1` like `TIE162P2`

```
*****Executing Job*****

Job Name                                      TIE162P1

*****Executing Job*****

Job Name                                      TIE162P2
Return Value                                  CCTV buitencameras
```

**Comment by marc4gov** [comment]
[log monax.pdf](https://github.com/monax/cli/files/1020066/log.monax.pdf)

As you can see, it passes some return values randomly

**Comment by compleatang** [comment]
This issue will be extremely hard to debug without a deterministic way for us to reproduce. If we can arrive at a deterministic way to reproduce happy to revisit at that time, but for now I'm not seeing anything we can utilize to track down the issue here.
