### ISSUE TITLE
Install problems

### ISSUE THREAD

**Issue by CromonMS** [monax/monax#1422]
Trying to install on Linux Mint (3.19.0-23-generic #37~14.04.1-Ubuntu) and it can't find the package after adding the repo.

go get github.com/monax/monax/cmd/monax 
doesn't work either to install from source, asks for github username and password.

Any ideas?

**Comment by zramsay** [comment]
there will be issues installing from source because we re-named the repo. This should be sorted by the next release. Try:
```
go get github.com/monax/monax
cd $GOPATH/src/github.com/monax/monax
git checkout develop
go install ./cmd/monax
```

Also, setting `export GIT_TERMINAL_PROMPT=1` in your `~/.profile`  or whatever help with the username/password thing

**Comment by zramsay** [comment]
closing as unresponsive
