### ISSUE TITLE
Chain seems corrupted even after monax clean command

### ISSUE THREAD

**Issue by cbruguera** [monax/monax#1423]
I'm running 4 nodes on different AWS instances. They were effectively connecting among themselves and allowing remote calls from the outside... Suddenly one node stopped working properly, failing to execute some contracts. The other nodes kept on running the chain and executing contract functions without issue.

I tried `monax clean` on the problematic node and then `monax chain start` with the same `init-dir`. The following screen shows the last lines of log output. The validator node fails to start.

![monax screenshot from 2017-06-16 16-50-03](https://user-images.githubusercontent.com/2256202/27245362-054356bc-52b9-11e7-826a-7db85479a56f.png)

After that, I tested doing the same on another node, `monax clean` and chain restart, but it also failed. My guess is that it fails because it's trying to connect to the "seed" which is the node that initially failed. Please confirm if this hypothesis makes sense.

In any case, I can't get the seed node running.

--
Docker version: 17.03.0-ce, build 3a232c8
Monax version: 0.17.0 (02a52b9)

**Comment by zramsay** [comment]
would need a deterministic script to debug.

**Comment by cbruguera** [comment]
@zramsay Is there an alternative way to "restart" the node apart from doing `monax clean` and `monax chain start` ?

**Comment by zramsay** [comment]
We had a `monax chains restart` command but all it did was:
```
monax chains stop myChain
monax chains start myChain
```

You can also `monax chains rm myChain` which will leave the data container around. That data container will be used by `monax chains start myChain`
