### ISSUE TITLE
Deprecation Warning: The use of the 'data' field

### ISSUE THREAD

**Issue by V-ess** [monax/monax#1424]
Please include in your bug report:

- [17.06.0-ce ] `docker version`
- [0.16.3] `monax version`
- [ ] `go version` (if applicable)
- [ ] `docker-machine version` (if applicable / !linux)
- [linux ubuntu ] operating system details (osx/windows/linux)
- [ instructions may be referencing deprecated syntax] what you expected to happen
- [ received message:
*****Executing Job*****
Job Name                                      setStorage
Deprecation Warning: The use of the 'data' field to specify the name of the contract function has been deprecated. Please update your epm.yaml file to use a combination of 'function' and 'data' fields instead. See documentation for further details.

*****Executing Job*****
Job Name                                      queryStorage
Deprecation Warning: The use of the 'data' field to specify the name of the contract function has been deprecated. Please update your epm.yaml file to use a combination of 'function' and 'data' fields instead. See documentation for further details.
Return Value                                  5
] what actually happened
- [ follow instructions from this url [https://monax.io/docs/getting-started/] which is showing this yaml:
- name: setStorage
  job:
    call:
      destination: $deployStorageK
      data: set $setStorageBase

- name: queryStorage
  job:
    query-contract:
      destination: $deployStorageK
      data: get

] steps to reproduction

If issue is a feature request, tell us why this feature is useful.

**Comment by zramsay** [comment]
fixed in #1425

**Comment by V-ess** [comment]
Thanks for letting me know.
