### ISSUE TITLE
Approach for the Keys in monax 

### ISSUE THREAD

**Issue by aniket-kumar** [monax/monax#1435]
I am working on monax and everytime i read about keys on any documentation of monax, i am getting that this can be used only at development not for the production. <a href = "https://monax.io/docs/known-chain-making/">Here </a> , i am getting that <br/>`Again, this is for demonstration purposes only, for a production system you will not do what we’re about to do.
`.<br/> So what should be the better approach for keys that can work on production as well. Please give a bit more insight around keys usage. Many thanks in advance !

**Comment by compleatang** [comment]
We aren't a security company and have a hard line rule here to not provide any advice.
