### ISSUE TITLE
Monax 0.18.0 does not compile contracts

### ISSUE THREAD

**Issue by JonasVdB** [monax/monax#1437]
## Environment
- [x] `docker version` = 17.07.0-ce 
- [x] `monax version`= 0.18.0
- [x] `go version` = 1.9
- [x] `docker-machine version`= 0.12.2
- [x] `operating system details` = macOS Sierra 10.12.5 (ubuntu 16.04 as well)

## What I expected to happen
* Compilation after using the `monax pkgs do --chain test_chain --address $addr --file deploy.yaml` command. 
* Showing of execution by CLI and creation of ./abi folder.

## What happened
No jobs where executed, no ./abi folder was created.
Output: 
```
*****Executing Job*****

Job Name                         defaultAddr
Writing [deploy.output.json]
```

## Steps to reproduce
This happened on both macOS as my ubuntu 16.04 vm, both running monax 0.18.0.
Creation of chain as follows:
```
monax chains make test_chain --chain-type simplechain
monax chains start test_chain --init-dir ~/.monax/chains/test_chain/test_chain_full_000
chain_dir=$HOME/.monax/chains/test_chain
chain_dir_this=$chain_dir/test_chain_full_000
addr=$(cat $chain_dir/addresses.csv | grep test_chain_full_000 | cut -d ',' -f 1)
monax pkgs do --chain test_chain --address $addr --file deploy.yaml
```

`monax chains logs -f test_chain` shows that the chain is running.

When using monax `0.17.0` on my macOS system, the same deploy.yaml file compiles smoothly.
This behaviour also appears when following step 3 from the  [getting started tutorial](https://monax.io/docs/getting-started/)

**Comment by Zohaib75** [comment]
Same issue on Ubuntu??? any solution???

**Comment by Airum** [comment]
Same issue, going to retry on 0.17

**Comment by compleatang** [comment]
In the future, remove the line that begins `jobs:` from that sample file and you'll be good to go.
