### ISSUE TITLE
Issues initializing monax

### ISSUE THREAD

**Issue by rudolph9** [monax/monax#1439]
Please include in your bug report:

- [ ] `docker version`: `Docker version 1.11.2, build b9f10c9`
- [ ] `monax version`: `Monax CLI Version: 0.18.0`
- [ ] `go version` (if applicable)
- [ ] `docker-machine version` (if applicable / !linux): `docker-machine version 0.13.0, build 9ba6da9`
- [ ] operating system details (osx/windows/linux): OSX 10.12.6
- [ ] what you expected to happen: monax to initialize
- [ ] what actually happened:
```
$ docker-machine ls
NAME    ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER    ERRORS
monax   -        virtualbox   Running   tcp://192.168.99.100:2376           v1.11.2
$ docker-machine env monax
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="/Users/rudolph9/.docker/machine/machines/monax"
export DOCKER_MACHINE_NAME="monax"
# Run this command to configure your shell:
# eval $(docker-machine env monax)
$ eval $(docker-machine env monax)
$ monax init
exit status 1
$ monax verbose
exit status 1
$ monax
exit status 1
```

If anyone can give me some feedback on why monax is simply returning `exit status 1` or perhaps how to better troubleshoot this I would greatly appreciate it.

**Comment by JonasVdB** [comment]
I recall having the same problem and it was fixed when calling the docker-machine '_default_' instead of '_monax_'. 
```
docker-machine create -d virtualbox default
eval $(docker-machine env default)
```
Does this help you?

**Comment by rudolph9** [comment]
Yes this fixes the issue.  Thank you for your help.
