### ISSUE TITLE
[core] deduplicate error messages; locate in an errors package

### ISSUE THREAD

**Issue by compleatang** [monax/monax#468]
**Problem** -- our error messages are not helpful (sometimes it is not our fault, sometimes it is). They do not always effectively communicate to a user what happened and how they should fix the problem. There is also a _boatload_ of redundancy in error messages.

**Solution** -- an error package should be used which should be the central repository for errors used within the stack. Errors should be registered such that their component area is known, the underlying error is known, and helpful "how to fix" messages can be displayed. This way will clean up the base code significantly. We also need to refactor how IfExit runs. When an error is returned to the outer layer we should always display three things for users:

(1) a custom cli err msg (e.g. "Error starting service"), 
(2) the actual error ("some docker API error"), and 
(3) what to do about it.

At the end we should display two links:

(a) to the docs site
(b) to our (upcoming) chat support site. (Once that is good and if we want to get frisky, we should include a `tell the marmots you got error code 439` or whatever message for users to cut and paste)

**Comment by zramsay** [comment]
have a pretty good idea about how to clean up / standardize the error messages but not sure what to do with IfExit

**Comment by zramsay** [comment]
use https://github.com/pkg/errors since that's what has been recommended by Dave Cheney in his talk on graceful error handling in go ... see `errors.Wrap()`
