### ISSUE TITLE
[chains] Better separation of chainID and chainName

### ISSUE THREAD

**Issue by compleatang** [monax/monax#858]
**Problem** -- `eris chains new` (currently, `start --init-dir` in coming release) imports to a chain directory in the data container that is the same as the chainName. However eris-db reads from a directory that maps to the chainID. Normally this does not present a problem in that our current paradigm mostly equivocates chainName and chainID. However, moving forward we need to have a stronger separation of the chainName (which should be human readable and really only known to cli) and the chainID (which should be machine optimized and utilized by db). The current edge case which eluciated the challenge is trying to run two nodes of the same chain on the same machine. Currently, the only real way to do this is as follows:

``` bash
eris chains new rps1 --dir rps/rps_full_000 --env CHAIN_ID=rps
eris chains stop rps1
eris data exec rps1 -- rm -rf /home/eris/.eris/chains/rps
eris data exec rps1 -- mv /home/eris/.eris/chains/rps1 /home/eris/.eris/chains/rps
eris chains start rps1
```

Then a user would perform a similar new, stop, exec, exec, start sequence on the second node. 

**Solution** -- I don't currently have a single proposed solution. I see a few options though and I'd like to solicity @benjaminbollen @silasdavis @pietv @zramsay 's opinions....
- _Option 1_ - add a flag to chains start which will determine what directory db should run "in".
- _Option 2_ - move to a single directory that **all** chains will run in, perhaps something like `/home/eris/.eris/chains/this` within the data container.
- _Option 3_ - have cli parse the `env` flag to see if there is a divergent `CHAIN_ID` variable given and do the data import to there.

Personally I think that Option 2 is cleanest all around as we should be able to assume one chain | one data container.

**Comment by zramsay** [comment]
related to #806

**Comment by infinius12345** [comment]
Hi,
When i use **eris chains new advchain1 --dir advchain/advchain_validator_000 --env CHAIN_ID=advchain**
it does not create a new dir under chains i only have a toml file
~/.eris/chains$ ll
total 32
drwxrwxr-x  6 infinius infinius 4096 Aug 11 09:24 ./
drwxrwxr-x 11 infinius infinius 4096 Aug  5 09:36 ../
drwxrwxr-x  2 infinius infinius 4096 Aug 11 07:38 account-types/
drwxr-xr-x 31 infinius infinius 4096 Aug 11 09:22 advchain/
-rw-rw-r--  1 infinius infinius  201 Aug 11 09:24 advchain1.toml
drwxrwxr-x  2 infinius infinius 4096 Aug 11 09:20 chain-types/
drwxrwxr-x  2 infinius infinius 4096 Aug 11 07:58 default/
-rw-rw-r--  1 infinius infinius  460 Aug  4 21:34 default.toml

so when i use
~/.eris/chains$ **eris data exec advchain1 -- mv /home/infinius/.eris/chains/advchain1 /home/infinius/.eris/chains/advchain**
mv: cannot stat '/home/infinius/.eris/chains/advchain1': No such file or directory
Container interactive-2129aecf-e28d-4b90-85b2-35766a1be069 exited with status 1

**Comment by zramsay** [comment]
this issue MUST solve #1133

**Comment by compleatang** [comment]
Closing this issue for now. This really needs to get handled in Burrow rather than by Monax.
