### ISSUE TITLE
[Keys] what do we do with it?

### ISSUE THREAD

**Issue by compleatang** [monax/monax#901]
**Problem** -- running keys via an exec service is slower than it needs to be. Particularly because keys should be ran as a daemon and everything should interact with it via it's API, not its command line interface (it's made to be a server). (This is related to this epic -> https://github.com/eris-ltd/eris-keys/issues/64 )

**Solution** -- we should interact with keys the way that we currently interact with IPFS; that is to say via an API client library that we import. Note that for testing purposes this will need to be mocked.

**Comment by zramsay** [comment]
bumping since keys will go in edb. This should wait until then.

**Comment by zramsay** [comment]
re-named because that's really the question we need to answer first

**Comment by VoR0220** [comment]
I say we create a reasonable JSON_RPC (maybe has some web3 options for the sake of portability and maybe tendermint/ABCI rpc methods?), that any client can simply implement themselves on their end for their key systems, and then they just swap in their key system. Ben's idea for this is a solid one and I back that horse. This way we can keep ours around for purely development purposes and we can get other signers on board.

**Comment by zramsay** [comment]
the repo _may_ move into hyperledger/burrow, however, I don't think we should do anything else other than that
